### ISSUE TITLE
Install via bower

### ISSUE THREAD

**Issue by juank11memphis** [juank11memphis/angular-jk-carousel#10]
Be able to install the component via bower, use code here as reference: https://github.com/juank11memphis/angular-jk-rating-stars

**Comment by maudel** [comment]
any update on this ?

**Comment by MadJlzz** [comment]
It is done since release v0.1.5.
Reference here : https://github.com/juank11memphis/angular-jk-carousel/releases

**Comment by juank11memphis** [comment]
I merged the pull request by @MadJlzz so the readme file is now updated to reflect bower changes. Thanks! :)

**Comment by maudel** [comment]
thanks a lot.
