### ISSUE TITLE
Slide-auto when only 1 image

### ISSUE THREAD

**Issue by sam2x** [juank11memphis/angular-jk-carousel#13]
Hi,

The carousel is sliding automatically when there is only 1 image, is that the normal behaviour ? How to disable slide when there is only 1 image ?

**Comment by Reda1000** [comment]
Hi,

cant reproduce in plunkr when used "Basic Carousel Setup" and removed images: https://plnkr.co/edit/7RoTcbu97pWh9doEwnkd?p=preview (Quick n Dirty Plunkring)

What is your directives setup? Normally auto sliding is off afaik. Did you try using `auto-slide="false"`?

**Comment by juank11memphis** [comment]
Hi Sam2x, Reda1000,

Thanks a lot for finding the issue and for trying to figure out what was going on. I just fixed the problems, now setting `auto-slide="false"` works as expected and when having a carousel with only one slide it wont slide at all.

Please update to 0.1.2 version to see these fixes.

Thanks a lot :)

**Comment by sam2x** [comment]
Thanks you for your swift answer! Can you confirm your patch ? i cant see 0.1.2  anywhere, or the related patch.
Regards

**Comment by juank11memphis** [comment]
Hi Sam2x, 
I am still new on how to handle npm packages, this is actually my first package, I just confirmed that the latest version of the package is 0.1.2, so what do you mean by the related patch?

**Comment by sam2x** [comment]
Hey Juan.

I was confused. I didnt notice you applied the modification on the branch "develop" (i was looking on the master branch), changes havent been merged.
Thanks for you commit.

Regards,
S

**Comment by juank11memphis** [comment]
Hi Sam, 

I just merged develop into master as well :)
