### ISSUE TITLE
Load url images dinamycally

### ISSUE THREAD

**Issue by ivanhdzd** [juank11memphis/angular-jk-carousel#16]
Hi, I'm using your carousel.
I need to upload it src images array from a database, and, when I load it array, carousel doesn't load it.
What can I do to fix it?

**Comment by juank11memphis** [comment]
Hi, 

I will review the problem and give you an answer as soon as possible, in case you find the problem please create a pull request.

Thanks a lot.

**Comment by ivanhdzd** [comment]
Hi.
I could already solve.
First load url images array, then inject your directive:

Add in the HTML file:
```
<div id="jk-carousel"></div>
```
Inside the controller:
```
var carousel = '<md-card layout=\"column\" layout-align=\"center center\" style=\"padding-top: 16px; padding-bottom: 16px;\">'
    + '<jk-carousel data=\"slides\" item-template-url=\"\'views\/templates\/item_jk_carousel.html\'\" max-width=\"800\" max-height=\"600\">'
    + '<\/jk-carousel><\/md-card>';

loadImages() // It's a promise
    .then(function(data) {
        $scope.slides = data;
        angular.element(document.getElementById('jk-carousel')).append($compile(carousel)($scope));
    });
```
Regards

**Comment by juank11memphis** [comment]
This should be fixed with this PR https://github.com/juank11memphis/angular-jk-carousel/pull/26 from @MadJlzz.
Closing the ticket.
