### ISSUE TITLE
Carousel is not loaded when server side data is feeded

### ISSUE THREAD

**Issue by technotomahi** [juank11memphis/angular-jk-carousel#22]
When the dataArray is filled by some http calls and it takes 1-2 secs to load the data , carousel is not getting initialized properly. 

For static data it works great

**Comment by technotomahi** [comment]
You might have to watch the data attribute value and reload the directive.

**Comment by LarryYangTw** [comment]
I fixed it!
Just add following code in jk-carousel.js file. 
```
  function CarouselDirective() {
    function link(scope, element, attrs, ctrl) {
      .................................................
      scope.$watch('ctrl.data', function () {
          ctrl.onDataChange();
      });

    }

```

**Comment by JohnBain** [comment]
I was able to solve this by simply fulfilling my service's promise _in the resolve_. No idea if this is a good practice or not, but I had the data immediately available in the controller.

**Comment by MadJlzz** [comment]
Since @LarryYangTw seems to be not answering, I've done the PR for him. Here is his correction : #26

**Comment by juank11memphis** [comment]
The PR was merged, closing this issue, thanks!
