### ISSUE TITLE
Left and Right arrows are  not working .

### ISSUE THREAD

**Issue by Gourav2906** [juank11memphis/angular-jk-carousel#33]

**Comment by OlegKonyk** [comment]
Those arrows relay on 'Material Icons'. Add a reference <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

**Comment by juank11memphis** [comment]
Hi @Gourav2906 the arrows depend on 'Material Icons', would you please confirm if adding that link fixes the issue for you? 
Thanks.

**Comment by pradeeptirmal** [comment]
ya. adding the font library should fix this issue
