### ISSUE TITLE
Importable package

### ISSUE THREAD

**Issue by DonHaron** [juank11memphis/angular-jk-carousel#35]
I recently used your package in a Meteor project. I had to adjust the package.json a bit to be able to import the package in a RequireJS way. Would you be interested in a pull request?

**Comment by juank11memphis** [comment]
Hi @DonHaron 

Sure that would be great, please feel free to create the PR.
Thanks

**Comment by DonHaron** [comment]
I opened a pull request a week ago, did you already have time to review it?
